# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qNRbzy--m3iDg-7ctsrd30eoFo0oVgRC

question 3
"""

month = { "jan" : 31 , "feb" : 28 , "march" : 31 , "april" : 30 , "may" : 31 , "june" : 30 , "july" : 31 , "aug" : 31 , "sept" : 30 , "oct" : 31 , "nov" : 30 , "dec" : 31}

mon = input("Enter the month name in short form :- ")
print("Number of days in ",mon,"=",month [ mon ])

month = { "jan" : 31 , "feb" : 28 , "march" : 31 , "april" : 30 , "may" : 31 , "june" : 30 , "july" : 31 , "aug" : 31 , "sept" : 30 , "oct" : 31 , "nov" : 30 , "dec" : 31}
keys_in_alphabetic_order = list ( month . keys() )
keys_in_alphabetic_order.sort()
print( keys_in_alphabetic_order )

month = { "jan" : 31 , "feb" : 28 , "march" : 31 , "april" : 30 , "may" : 31 , "june" : 30 , "july" : 31 , "aug" : 31 , "sept" : 30 , "oct" : 31 , "nov" : 30 , "dec" : 31}

print( "Month which have 31 days are: ")
for i in month :
    if month [ i ] == 31 :
        print( i )

month = { "jan" : 31 , "feb" : 28 , "march" : 31 , "april" : 30 , "may" : 31 , "june" : 30 , "july" : 31 , "aug" : 31 , "sept" : 30 , "oct" : 31 , "nov" : 30 , "dec" : 31}

print("Month according to number of days are: ")
print("feb")
for i in month :
    if month [ i ] == 30 :
        print(i)
for i in month :
    if month [ i ] == 31 :
        print( i)

"""question 14"""

d=[{'name':'Todd', 'phone':'555-1414', 'email':'todd@mail.net'},
{'name':'Helga', 'phone':'555-1618', 'email':'helga@mail.net'},
{'name':'Princess', 'phone':'555-3141', 'email':''},
{'name':'LJ', 'phone':'555-2718', 'email':'lj@mail.net'}]
print("The users whose phone number ends in 8 are: ")
for i in d:
  if i["phone"].endswith('8'):
    print(i['name'])

d=[{'name':'Todd', 'phone':'555-1414', 'email':'todd@mail.net'},
{'name':'Helga', 'phone':'555-1618', 'email':'helga@mail.net'},
{'name':'Princess', 'phone':'555-3141', 'email':''},
{'name':'LJ', 'phone':'555-2718', 'email':'lj@mail.net'}]
for i in d:
  if i["email"]=='':
    print(i["name"])

"""question 1"""

Total_products=eval(input("Enter the number of products: "))
dict={}
for i in range(Total_products):
  name=input("Enter the name of the product: ")
  price=eval(input("Enter the price of the product: "))
  dict[name]=price             

# while true is used for repetition as in the question
while True:
  namecheck=input("Enter the product name for the price: ")
  if namecheck in dict:
    print("The price of ",namecheck," is",dict[name])
  else:
    print("The entered product is not in the entered dictionary. ")
    break

"""question 6"""

num_of_teams =int(input("Enter Number Of Teams: "))
total_teams_dict={}
for team in range(num_of_teams):
    team_name = input("Enter Team name: ")
    team_score =[]
    wins = int(input("Enter Win: "))
    losses = int(input("Enter Losses: "))
    team_score.extend((wins,losses))
    total_teams_dict.update({team_name:team_score})

print(total_teams_dict)

"""question 2"""

Total_products=eval(input("Enter the number of products: "))
dict1={}
for i in range(Total_products):
  name=input("Enter the name of the product: ")
  price=eval(input("Enter the price of the product: "))
  dict1[name]=price             

for i in range(Total_products):
  namecheck=input("Enter the product name for the price: ")
  if namecheck in dict1:
    print("The price of ",namecheck," is",dict1[name])
  else:
    print("The entered product is not in the entered dictionary. ")

print(dict1)

amount1 = eval(input("Enter a dollar amount: "))
for key ,values in dict1.items():
    if  int(values) < amount1:
        print (key ,"->",values)

"""question 4"""

d1={"user1":1,"user2":2,"user3":3,"user4":4,"user5":5,"user6":5,"user7":7,"user8":8,"user9":9,"user10":10}
username=input("Enter your username : ")
if username  not in d1.keys():
    print("you are not a valid user of the system.")
else:
    password=eval(input("Enter your password :"))
    if password in d1.values() and username in d1.keys():
        print("You have sucessfully logged in")
    else:
        print("you entered wrong password ")

"""question 5(A)"""

no_of_teams = eval(input("Enter the number of teams: "))
team_scores = {}
for i in range(no_of_teams):
  team_name = input("Enter the team's name: ")
  wins = int(input("Enter number of wins: "))
  losses = int(input("Enter number of losses: "))
  team_scores[team_name] = [wins, losses]

team_find = input("Enter the name of the team: ")
print("Team ", team_find, "'s winning percentage = ", (team_scores[team_find][0]/sum(team_scores[team_find]))*100)

"""question 5(B)"""

winning_team = [i[0] for i in team_scores.values()]
print(winning_team)

"""question 5(C)"""

winning_record = []
for i in team_scores:
  if team_scores[i][0]>0:
    winning_record.append(i)
    print(winning_record)

"""question 7"""

list1=[1,2,3,4,5
    ,6,7,8,9,0
    ,2,5,8,3,9
    ,9,5,3,2,7
    ,3,4,7,5,8]
dict1={}
for i in range(len(list1)):
  if i in list1:
    dict1[i]=list1.count(i)
print(dict1)

"""question 8"""

import random
cards = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5,"Six":6,"Seven":7,"Eight":8,"Nine":9,"Ten":10}
cards_each = 3
player1card =[]
player2card =[]
for card in range(cards_each):
    card1 = random.choice(list(cards.values()))
    card2 = random.choice(list(cards.values()))
    player1card.append(card1)
    player2card.append(card2)
print(player1card,player2card)

if sum(player1card)>sum(player2card):
    print("Player 1 wins with ",sum(player1card)," against Player 2 with",sum(player2card))
elif sum(player2card)>sum(player1card):
    print("Player 2 wins with ",sum(player2card)," against Player 1 with",sum(player1card))

"""question 9"""

